### ISSUE TITLE
Steam Store API

### ISSUE THREAD

**Issue by Revadike** [xPaw/SteamWebAPIDocumentation#3]
Why did you choose to not document this? 
It may not follow the structure of the other listed API, but it would be handy to have this included too.

Some examples:
 * Everything listed here: https://wiki.teamfortress.com/wiki/User:RJackson/StorefrontAPI
 * https://store.steampowered.com/api/libraryappdetails/?appid=440&l=english
 * https://store.steampowered.com/points/heroimage?appid=440
 * https://store.steampowered.com/dynamicstore/userdata (requires web authentication)
 * https://store.steampowered.com/ajaxrequestplaytestaccess/440 (requires POST)
 * https://store.steampowered.com/checkout/addfreelicense/0 (requires POST)

Btw, what's up with the execute button not including the prefilled api key?

**Comment by xPaw** [comment]
These store apis do not follow any logical structure. This thing is only about the `api.steampowered.com` APIs.

> Btw, what's up with the execute button not including the prefilled api key?

Works fine here.

**Comment by Revadike** [comment]
Too bad, would've been nice to have everything available at one place.

> Works fine here.

For some reason it's using my access token, while it should be using my api key:
![image](https://user-images.githubusercontent.com/4411977/108610206-2cfd7080-73d4-11eb-8ec5-00722900b5b8.png)
I also checked `localStorage` and it's all correctly set there.

**Comment by Revadike** [comment]
I guess we have [this](https://github.com/SteamDatabase/SteamTracking/blob/master/ClientExtracted/public/url_list.txt).

**Comment by xPaw** [comment]
> For some reason it's using my access token

Clear it out then. That's what it's supposed to do.

**Comment by Revadike** [comment]
Huh? Why?
I expect it to be used with methods that actually require it.

**Comment by Revadike** [comment]
https://github.com/Revadike/UnofficialSteamWebAPI
