### ISSUE TITLE
[Bug] wrong URL

### ISSUE THREAD

**Issue by Revadike** [xPaw/SteamWebAPIDocumentation#4]
For example:
![image](https://user-images.githubusercontent.com/4411977/161178250-0c83d26e-b928-4f67-a524-2dc4930c9023.png)

Opens/executes the following page:
`https://api.steampowered.com/IStoreService/GetAppList/v1/?key=XXX&include_hardware=1`

I expect several other parameters with `0` as value.
Also, booleans mismatch between false/true and 0/1, but that's not really an issue.

**Comment by RudeySH** [comment]
I don't know if any of the booleans in GetOwnedGames change the result when explicitly set to 0, but I'd like to add that 0 will make a difference here:

`https://api.steampowered.com/IPlayerService/GetOwnedGames/v1/?steamid=76561198044364065&skip_unvetted_apps=0`

GetOwnedGames always skips "unvetted" apps unless `skip_unvetted_apps` is explicitly set to 0.

I checked to see if GetSupportedAPIList returns information about what booleans are 1 by default, but unfortunately it does not:

```json
{"name":"skip_unvetted_apps","type":"bool","optional":true,"description":"if set, skip unvetted store apps"}
```

**Comment by Revadike** [comment]
https://api.steampowered.com/IStoreService/GetAppList/v1/?key=XXX&include_hardware=true

vs

https://api.steampowered.com/IStoreService/GetAppList/v1/?key=XXX&include_games=false&include_dlc=false&include_software=false&include_videos=false&include_hardware=true

is definitely different.

**Comment by RudeySH** [comment]
I see, good to know.

Thanks for the quick improvement @xPaw!
